/**
 * scripts/build-db.js
 *
 * Downloads the free DB-IP City Lite CSV (no account needed) and
 * outputs site/db.js — a self-contained JS file that sets window.__IPDB__
 *
 * Run monthly to refresh:
 *   node scripts/build-db.js
 *
 * Then commit + push — GitHub Pages serves the updated db.js automatically.
 *
 * Data: https://db-ip.com/db/lite.php (CC BY 4.0)
 */

import https from 'https';
import fs from 'fs';
import path from 'path';
import zlib from 'zlib';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE  = path.resolve(__dirname, '../site/db.js');
const TMP_CSV   = path.resolve(__dirname, '../_tmp.csv');

function getDownloadURL() {
  const now   = new Date();
  const year  = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  return `https://download.db-ip.com/free/dbip-city-lite-${year}-${month}.csv.gz`;
}

function ipToInt(ip) {
  return ip.split('.').reduce((acc, o) => (acc * 256 + parseInt(o, 10)) >>> 0, 0);
}

async function download(url, dest) {
  return new Promise((resolve, reject) => {
    console.log(`Downloading: ${url}`);
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return download(res.headers.location, dest).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`HTTP ${res.statusCode} — try again tomorrow if the monthly file isn't up yet.`));
      }
      const out = fs.createWriteStream(dest);
      res.pipe(zlib.createGunzip()).pipe(out);
      out.on('finish', () => { out.close(); resolve(); });
      out.on('error', reject);
    }).on('error', reject);
  });
}

async function build() {
  await download(getDownloadURL(), TMP_CSV);

  console.log('Parsing CSV...');

  const rl = readline.createInterface({
    input: fs.createReadStream(TMP_CSV),
    crlfDelay: Infinity,
  });

  const ranges = [];
  let count = 0;

  for await (const line of rl) {
    if (!line.trim()) continue;
    const p = line.split(',').map(s => s.replace(/^"|"$/g, '').trim());
    if (p.length < 8) continue;

    const [ipStart, ipEnd, cc, country, region, city, lat, lon, tz] = p;

    // Skip IPv6 — too large for a simple static JS file
    if (ipStart.includes(':')) continue;

    let s, e;
    try {
      s = ipToInt(ipStart);
      e = ipToInt(ipEnd);
    } catch { continue; }

    // Compact array format: [start, end, cc, country, region, city, lat, lon, tz]
    ranges.push([
      s, e,
      cc      || null,
      country || null,
      region  || null,
      city    || null,
      lat     ? parseFloat(lat) : null,
      lon     ? parseFloat(lon) : null,
      tz      || null,
    ]);

    count++;
    if (count % 100_000 === 0) process.stdout.write(`  ${count.toLocaleString()} ranges...\r`);
  }

  console.log(`\n  Total IPv4 ranges: ${ranges.length.toLocaleString()}`);
  console.log('Writing site/db.js...');

  const js = `// Auto-generated by scripts/build-db.js — do not edit manually.
// Source: DB-IP City Lite (https://db-ip.com) — CC BY 4.0
// Generated: ${new Date().toISOString()}
window.__IPDB__ = ${JSON.stringify(ranges)};
`;

  fs.writeFileSync(OUT_FILE, js);
  fs.unlinkSync(TMP_CSV);

  const mb = (fs.statSync(OUT_FILE).size / 1_048_576).toFixed(1);
  console.log(`\nDone! site/db.js — ${mb} MB`);
  console.log('\nNext steps:');
  console.log('  git add site/db.js');
  console.log('  git commit -m "Update IP database"');
  console.log('  git push\n');
}

build().catch(err => {
  console.error('\n[error]', err.message);
  try { fs.unlinkSync(TMP_CSV); } catch {}
  process.exit(1);
});
