import {useEffect,useMemo,useState} from 'react';
import {Archive,AtSign,ChevronLeft,ChevronRight,Clock3,File,Folder,Inbox as InboxIcon,LogOut,Mail,Menu,Paperclip,Plus,RefreshCw,Search,Send,Settings,ShieldAlert,Star,Trash2,UserPlus,X,MoreHorizontal} from 'lucide-react';
import {supabase,supabaseConfigured,authIdentity,mailAddress,MAIL_DOMAIN,initials} from './lib';

type Message={id:string;sender:string;sender_name?:string;recipients:string[];subject:string;body_text?:string;body_html?:string;is_read:boolean;is_starred:boolean;is_archived:boolean;is_spam:boolean;is_deleted:boolean;received_at:string;folder?:string;attachments?:Attachment[]};
type Attachment={id:string;filename:string;content_type:string;size:number;storage_path:string};
type Settings={theme:string;accent:string;density:string;reading_pane:string;show_avatars:boolean;show_previews:boolean};
const defaultSettings:Settings={theme:'dark',accent:'#ffffff',density:'comfortable',reading_pane:'right',show_avatars:true,show_previews:true};

function App(){
 if(!supabaseConfigured || !supabase) return <SetupScreen/>;
 const [session,setSession]=useState<any>(null); const [username,setUsername]=useState(''); const [profile,setProfile]=useState<any>(null); const [settings,setSettings]=useState<Settings>(defaultSettings); const [view,setView]=useState('inbox'); const [selected,setSelected]=useState<Message|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [compose,setCompose]=useState(false); const [auth,setAuth]=useState<'login'|'signup'>('login'); const [authUser,setAuthUser]=useState(''); const [password,setPassword]=useState(''); const [displayName,setDisplayName]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [mobileList,setMobileList]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session); if(data.session) load(data.session.user.id); else setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s); if(s) load(s.user.id); else {setProfile(null);setMessages([]);setLoading(false)}}); return()=>subscription.unsubscribe()},[]);
 async function load(uid:string){setLoading(true); const [{data:p},{data:s},{data:m}]=await Promise.all([supabase.from('profiles').select('*').eq('id',uid).single(),supabase.from('user_settings').select('*').eq('user_id',uid).single(),supabase.from('messages').select('*, attachments(*)').eq('mailbox_user_id',uid).eq('is_deleted',false).order('received_at',{ascending:false})]); setProfile(p); setUsername(p?.username||''); if(s)setSettings({...defaultSettings,...s}); setMessages((m||[]) as Message[]); setLoading(false)}
 async function doAuth(e:React.FormEvent){e.preventDefault();setError('');setLoading(true);try{const u=authUser.toLowerCase().trim(); if(!/^[a-z0-9_]{3,24}$/.test(u)) throw new Error('Username must be 3–24 characters: letters, numbers, underscores.'); if(auth==='signup'){if(password.length<8)throw new Error('Password must be at least 8 characters.'); const {data,error}=await supabase.auth.signUp({email:authIdentity(u),password,options:{data:{username:u,display_name:displayName||u}}}); if(error)throw error; if(data.user){await supabase.from('profiles').upsert({id:data.user.id,username:u,display_name:displayName||u}); await supabase.from('user_settings').upsert({user_id:data.user.id,...defaultSettings});} } else {const {error}=await supabase.auth.signInWithPassword({email:authIdentity(u),password});if(error)throw error}}catch(err:any){setError(err.message||'Something went wrong.')}finally{setLoading(false)}}
 async function signOut(){await supabase.auth.signOut();setSelected(null)}
 const filtered=useMemo(()=>{let a=messages; if(view==='starred')a=a.filter(x=>x.is_starred); if(view==='sent')a=a.filter(x=>x.folder==='sent'); if(view==='trash')a=a.filter(x=>x.is_deleted); if(view==='spam')a=a.filter(x=>x.is_spam); if(view==='archive')a=a.filter(x=>x.is_archived); if(view==='inbox')a=a.filter(x=>!x.is_archived&&!x.is_spam&&!x.is_deleted&&x.folder!=='sent'); if(search)a=a.filter(x=>(x.subject+' '+x.sender+' '+(x.body_text||'')).toLowerCase().includes(search.toLowerCase())); return a},[messages,view,search]);
 async function markRead(m:Message){if(!m.is_read){await supabase.from('messages').update({is_read:true}).eq('id',m.id);setMessages(v=>v.map(x=>x.id===m.id?{...x,is_read:true}:x))}setSelected(m);setMobileList(false)}
 async function toggleStar(m:Message){await supabase.from('messages').update({is_starred:!m.is_starred}).eq('id',m.id);setMessages(v=>v.map(x=>x.id===m.id?{...x,is_starred:!x.is_starred}:x));if(selected?.id===m.id)setSelected({...m,is_starred:!m.is_starred})}
 async function saveSettings(next:Settings){setSettings(next);await supabase.from('user_settings').upsert({user_id:session.user.id,...next})}
 if(!session)return <Auth auth={auth} setAuth={setAuth} authUser={authUser} setAuthUser={setAuthUser} password={password} setPassword={setPassword} displayName={displayName} setDisplayName={setDisplayName} error={error} loading={loading} submit={doAuth}/>;
 return <div className={`app ${settings.theme}`} style={{'--accent':settings.accent} as React.CSSProperties}>
  <header className="topbar"><button className="iconbtn mobileOnly" onClick={()=>setMobileList(true)}><Menu size={20}/></button><div className="brand"><div className="logo"><AtSign size={18}/></div><span>Encode Mail</span></div><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search mail"/></div><button className="iconbtn" onClick={()=>load(session.user.id)}><RefreshCw size={18}/></button><button className="iconbtn" onClick={()=>setView('settings')}><Settings size={18}/></button><button className="avatar" title="Sign out" onClick={signOut}>{initials(profile?.display_name,username)}</button></header>
  <div className="layout">
   <aside className={`sidebar ${mobileList?'open':''}`}><button className="close mobileOnly" onClick={()=>setMobileList(false)}><X/></button><button className="compose" onClick={()=>setCompose(true)}><Plus size={18}/>Compose</button><Nav icon={<InboxIcon/>} text="Inbox" count={messages.filter(x=>!x.is_read&&!x.is_archived&&!x.is_spam&&!x.is_deleted).length} active={view==='inbox'} onClick={()=>setView('inbox')}/><Nav icon={<Star/>} text="Starred" active={view==='starred'} onClick={()=>setView('starred')}/><Nav icon={<Send/>} text="Sent" active={view==='sent'} onClick={()=>setView('sent')}/><Nav icon={<File/>} text="Drafts" active={view==='drafts'} onClick={()=>setView('drafts')}/><div className="sideTitle">Folders</div><Nav icon={<Archive/>} text="Archive" active={view==='archive'} onClick={()=>setView('archive')}/><Nav icon={<ShieldAlert/>} text="Spam" active={view==='spam'} onClick={()=>setView('spam')}/><Nav icon={<Trash2/>} text="Trash" active={view==='trash'} onClick={()=>setView('trash')}/><div className="sideTitle">Account</div><Nav icon={<Settings/>} text="Customize" active={view==='settings'} onClick={()=>setView('settings')}/><div className="accountCard"><b>{username}@{MAIL_DOMAIN}</b><span>{profile?.display_name||username}</span></div></aside>
   <main className="content">{view==='settings'?<SettingsPanel settings={settings} save={saveSettings} username={username}/>:<><div className="mailHeader"><div><h2>{view[0].toUpperCase()+view.slice(1)}</h2><span>{filtered.length} messages</span></div><button className="iconbtn"><MoreHorizontal/></button></div><div className={`mailarea ${selected?'hasSelected':''}`}><section className={`list ${mobileList?'show':''}`}>{filtered.length===0?<div className="empty"><Mail size={40}/><h3>No mail here</h3><p>Your {view} is empty.</p></div>:filtered.map(m=><MessageRow key={m.id} m={m} selected={selected?.id===m.id} settings={settings} click={()=>markRead(m)} star={()=>toggleStar(m)}/>)}</section>{selected&&<section className={`reader ${!mobileList?'show':''}`}><button className="back mobileOnly" onClick={()=>setMobileList(true)}><ChevronLeft/>Back</button><Reader m={selected} onClose={()=>{setSelected(null);setMobileList(true)}} onStar={()=>toggleStar(selected)}/></section>}</div></>}</main>
  </div>{compose&&<Compose user={profile} username={username} onClose={()=>setCompose(false)} onSent={()=>{setCompose(false);load(session.user.id)}}/>}
 </div>
}
function SetupScreen(){return <div className="setupScreen"><div className="setupCard"><div className="logo big"><AtSign/></div><h1>Encode Mail</h1><p>Supabase is not connected to this deployment yet.</p><div className="setupSteps"><div><b>1.</b><span>Open GitHub → Settings → Secrets and variables → Actions.</span></div><div><b>2.</b><span>Add <code>VITE_SUPABASE_URL</code> and <code>VITE_SUPABASE_ANON_KEY</code>.</span></div><div><b>3.</b><span>Re-run the GitHub Pages workflow.</span></div></div><p className="muted">The app intentionally shows this screen instead of a blank page when the public Supabase variables are missing.</p></div></div>}
function Nav({icon,text,count,active,onClick}:{icon:any;text:string;count?:number;active:boolean;onClick:()=>void}){return <button className={`nav ${active?'active':''}`} onClick={onClick}>{icon}<span>{text}</span>{count? <b>{count}</b>:null}</button>}
function MessageRow({m,selected,settings,click,star}:{m:Message;selected:boolean;settings:Settings;click:()=>void;star:()=>void}){return <div className={`messageRow ${selected?'selected':''} ${m.is_read?'read':''} ${settings.density}`} onClick={click}><div className="rowAvatar">{initials(m.sender_name,m.sender)}</div><div className="rowMain"><div className="rowTop"><strong>{m.sender_name||m.sender}</strong><span>{new Date(m.received_at).toLocaleDateString()}</span></div><div className="subject">{m.subject||'(no subject)'}</div>{settings.show_previews&&<div className="preview">{(m.body_text||'').slice(0,100)}</div>}</div><button className={`star ${m.is_starred?'on':''}`} onClick={e=>{e.stopPropagation();star()}}><Star size={17}/></button></div>}
function Reader({m,onClose,onStar}:{m:Message;onClose:()=>void;onStar:()=>void}){return <div className="readerInner"><div className="readerHead"><div><h1>{m.subject||'(no subject)'}</h1><span>{new Date(m.received_at).toLocaleString()}</span></div><div className="actions"><button className={`iconbtn ${m.is_starred?'starOn':''}`} onClick={onStar}><Star/></button><button className="iconbtn" onClick={onClose}><X/></button></div></div><div className="senderLine"><div className="rowAvatar">{initials(m.sender_name,m.sender)}</div><div><b>{m.sender_name||m.sender}</b><small>{m.sender}</small></div></div><div className="body">{m.body_html?<div dangerouslySetInnerHTML={{__html:m.body_html}}/>:<p>{m.body_text}</p>}</div>{m.attachments?.length?<div className="attachments">{m.attachments.map(a=><div className="attachment" key={a.id}><Paperclip size={16}/><span>{a.filename}</span><small>{Math.round(a.size/1024)} KB</small></div>)}</div>:null}<div className="readerBottom"><button className="secondary">↩ Reply</button><button className="secondary">↪ Forward</button></div></div>}
function Compose({user,username,onClose,onSent}:{user:any;username:string;onClose:()=>void;onSent:()=>void}){const [to,setTo]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');const [files,setFiles]=useState<File[]>([]);const [sending,setSending]=useState(false);const [err,setErr]=useState('');async function send(){setErr('');setSending(true);try{if(!to.trim())throw new Error('Recipient is required.');const recipients=to.split(',').map(x=>x.trim()).filter(Boolean);const {data,error}=await supabase.functions.invoke('send-email',{body:{to:recipients,subject,body_text:body}});if(error)throw error;if(data?.error)throw new Error(data.error);onSent()}catch(e:any){setErr(e.message||'Could not send message.')}finally{setSending(false)}}return <div className="modal"><div className="composeBox"><div className="composeHead"><b>New message</b><button className="iconbtn" onClick={onClose}><X/></button></div><input placeholder="To" value={to} onChange={e=>setTo(e.target.value)}/><input placeholder="Subject" value={subject} onChange={e=>setSubject(e.target.value)}/><textarea autoFocus placeholder="Write your message…" value={body} onChange={e=>setBody(e.target.value)}/><div className="composeFoot"><label className="iconbtn"><Paperclip/><input hidden type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label><span>{files.length?`${files.length} attachment(s)`:''}</span><span className="grow"/>{err&&<span className="error">{err}</span>}<button className="send" disabled={sending} onClick={send}>{sending?'Sending…':'Send'}<Send size={16}/></button></div></div></div>}
function SettingsPanel({settings,save,username}:{settings:Settings;save:(x:Settings)=>void;username:string}){const [s,setS]=useState(settings);useEffect(()=>setS(settings),[settings]);function upd<K extends keyof Settings>(k:K,v:Settings[K]){const n={...s,[k]:v};setS(n);save(n)}return <div className="settings"><div className="mailHeader"><div><h2>Customize</h2><span>Make Encode Mail yours.</span></div></div><div className="settingsGrid"><div className="settingCard"><h3>Appearance</h3><label>Theme<select value={s.theme} onChange={e=>upd('theme',e.target.value)}><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Accent<input type="color" value={s.accent} onChange={e=>upd('accent',e.target.value)}/></label><label>Inbox density<select value={s.density} onChange={e=>upd('density',e.target.value)}><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="spacious">Spacious</option></select></label></div><div className="settingCard"><h3>Inbox</h3><Toggle label="Show message previews" value={s.show_previews} onChange={v=>upd('show_previews',v)}/><Toggle label="Show avatars" value={s.show_avatars} onChange={v=>upd('show_avatars',v)}/><label>Reading pane<select value={s.reading_pane} onChange={e=>upd('reading_pane',e.target.value)}><option value="right">Right</option><option value="bottom">Bottom</option><option value="hidden">Hidden</option></select></label></div><div className="settingCard"><h3>Mailbox</h3><p>Your address</p><div className="addressBox">{mailAddress(username)}</div><small>Username/password accounts are handled through Supabase. Your public mailbox address uses @{MAIL_DOMAIN}.</small></div></div></div>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><i/></label>}
function Auth({auth,setAuth,authUser,setAuthUser,password,setPassword,displayName,setDisplayName,error,loading,submit}:{auth:'login'|'signup';setAuth:any;authUser:string;setAuthUser:any;password:string;setPassword:any;displayName:string;setDisplayName:any;error:string;loading:boolean;submit:(e:React.FormEvent)=>void}){return <div className="auth"><div className="authCard"><div className="logo big"><AtSign/></div><h1>Encode Mail</h1><p className="muted">Private mailboxes on <b>@{MAIL_DOMAIN}</b>.</p><div className="tabs"><button className={auth==='login'?'on':''} onClick={()=>setAuth('login')}>Sign in</button><button className={auth==='signup'?'on':''} onClick={()=>setAuth('signup')}>Create account</button></div><form onSubmit={submit}>{auth==='signup'&&<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name (optional)"/>}<input required autoCapitalize="none" value={authUser} onChange={e=>setAuthUser(e.target.value)} placeholder="Username"/><div className="suffix">@{MAIL_DOMAIN}</div><input required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)"/>{error&&<div className="errorBox">{error}</div>}<button className="primary" disabled={loading}>{loading?'Working…':auth==='login'?'Sign in':'Create mailbox'}</button></form><small className="muted">No email address is required for signup. Save your recovery method once you add one.</small></div></div>}
export default App;
